# Generated by Django 4.0.6 on 2022-07-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
        migrations.CreateModel(
            name='CartMe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priceTotal', models.PositiveIntegerField(blank=True, help_text='price total', null=True, verbose_name='priceTotal')),
                ('discount', models.CharField(help_text='discount', max_length=10, verbose_name='discount')),
                ('date', models.DateTimeField(auto_now=True, help_text='date')),
                ('ispaid', models.BooleanField(default=False, help_text='ispaid')),
                ('factor', models.JSONField(blank=True, help_text='Purchase Invoice', null=True, verbose_name='factor')),
            ],
            options={
                'verbose_name': 'Cart',
                'verbose_name_plural': 'Carts',
            },
        ),
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True, help_text='date')),
                ('date_update', models.DateTimeField(auto_now=True, help_text='date update')),
                ('cartme', models.ManyToManyField(help_text='products', to='cart.cartme')),
            ],
            options={
                'verbose_name': 'History',
                'verbose_name_plural': 'Historys',
            },
        ),
    ]
