# Generated by Django 4.0.6 on 2022-07-28 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='HistorytoCustomer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartme',
            name='product',
            field=models.ManyToManyField(help_text='products', through='cart.CartItem', to='product.product'),
        ),
        migrations.AddField(
            model_name='cartme',
            name='user',
            field=models.ForeignKey(blank=True, help_text='user name', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CartmetoCustomer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='cart',
            field=models.ForeignKey(help_text='cart', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CartItemtoCartMe', to='cart.cartme'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='product',
            field=models.ForeignKey(help_text='products', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='CartItemtoProduct', to='product.product'),
        ),
        migrations.AddField(
            model_name='cartitem',
            name='salesman',
            field=models.ForeignKey(blank=True, help_text='salesman', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
    ]
