# Generated by Django 4.0.6 on 2022-07-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('product', '0001_initial'),
        ('comment', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='rate',
            name='product',
            field=models.ManyToManyField(to='product.product'),
        ),
    ]
