# Generated by Django 4.0.6 on 2022-08-02 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, help_text='phone number', null=True),
        ),
    ]
