# Generated by Django 4.0.6 on 2022-08-03 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_alter_user_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_email_verified',
        ),
        migrations.AlterField(
            model_name='otp',
            name='type',
            field=models.IntegerField(choices=[(1, 'REGISTER'), (2, 'LOGIN')], help_text='type', verbose_name='type'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, max_length=254, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.PositiveBigIntegerField(blank=True, help_text='phone number', null=True, unique=True, verbose_name='phone number'),
        ),
    ]
