# Generated by Django 4.0.6 on 2022-08-03 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='exp_time',
            field=models.DateTimeField(help_text='Time out', verbose_name='exp_time'),
        ),
    ]
