# Generated by Django 4.0.6 on 2022-08-09 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_otp_exp_time_error'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='exp_time_error',
            new_name='exp_time_error1',
        ),
        migrations.AddField(
            model_name='otp',
            name='exp_time_error2',
            field=models.DateTimeField(blank=True, help_text='Time out', null=True, verbose_name='exp_time_error'),
        ),
        migrations.AddField(
            model_name='otp',
            name='number_error_code',
            field=models.PositiveIntegerField(blank=True, help_text='number_error_code', null=True, verbose_name='number_error_code'),
        ),
    ]
