# Generated by Django 4.0.6 on 2022-08-10 05:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_rename_exp_time_error_otp_exp_time_error1_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='otp',
            old_name='number_error_code',
            new_name='number_error_code3',
        ),
        migrations.AddField(
            model_name='otp',
            name='number_error_code5',
            field=models.PositiveIntegerField(blank=True, help_text='number_error_code', null=True, verbose_name='number_error_code'),
        ),
    ]
