# Generated by Django 4.0.6 on 2022-08-10 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_rename_number_error_code_otp_number_error_code3_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='number_error_code3',
            field=models.PositiveIntegerField(blank=True, help_text='number_error_code3', null=True, verbose_name='number_error_code3'),
        ),
        migrations.AlterField(
            model_name='otp',
            name='number_error_code5',
            field=models.PositiveIntegerField(blank=True, help_text='number_error_code5', null=True, verbose_name='number_error_code5'),
        ),
    ]
