# Generated by Django 4.0.6 on 2022-07-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, help_text='Enter your Address', max_length=255, null=True, verbose_name='address')),
                ('phone_number', models.PositiveBigIntegerField(blank=True, help_text='Enter your phone number', null=True, verbose_name='phone_number')),
                ('image', models.ImageField(blank=True, help_text='Upload your photo', null=True, upload_to='Introduction/Intro')),
                ('discription', models.TextField(blank=True, help_text='Enter your discription', null=True, verbose_name='discretion')),
            ],
            options={
                'verbose_name': 'Introduction',
                'verbose_name_plural': 'Introductions',
            },
        ),
    ]
