# Generated by Django 4.0.6 on 2022-07-28 05:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wishlist',
            name='user',
            field=models.ForeignKey(blank=True, help_text='user', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wishlisttocustomer', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='property',
            name='cat_id',
            field=models.ForeignKey(blank=True, help_text='category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='propertytocat', to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='cat',
            field=models.ForeignKey(help_text='category', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='producttocat', to='product.category'),
        ),
        migrations.AddField(
            model_name='product',
            name='color',
            field=models.ManyToManyField(help_text='Choose the color of your product', to='product.color'),
        ),
        migrations.AddField(
            model_name='details',
            name='pro_id',
            field=models.ForeignKey(help_text='property', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='detailstoproperty', to='product.property'),
        ),
        migrations.AddField(
            model_name='details',
            name='product_id',
            field=models.ManyToManyField(to='product.product'),
        ),
        migrations.AddField(
            model_name='category',
            name='category_p',
            field=models.ForeignKey(blank=True, help_text='Please select the desired product type', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='catproductmodel', to='product.category', verbose_name='title'),
        ),
    ]
